### ISSUE TITLE
Major Issue: Export to CX bug

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#102]
Cytoscape 3.7.1
WikiPathways App 3.3.7

### This fails:
* Import WP554 as pathway
* Export > Network to File (choose CX)

Look at the last few lines of the CX file, and you'll see an error.

### This succeeds:
1) Import WP554 as pathway
2) Save
3) Close
4) Re-open the session file from 2
5) Export > Network to File (choose CX)

**Comment by AlexanderPico** [comment]
@AdamStuart This is definitely a bug we saw before. I think it occured during session saving...  The fix might need to be applied to exporting to CX, XGMML and other network file formats as well.

**Comment by ariutta** [comment]
Another test case: `WP244`

**Comment by AdamStuart** [comment]
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
	at org.cytoscape.view.presentation.property.IntegerVisualProperty.toSerializableString(IntegerVisualProperty.java:1)
	at org.cytoscape.io.internal.cx_writer.VisualPropertiesGatherer.addProperties(VisualPropertiesGatherer.java:101)
	at org.cytoscape.io.internal.cx_writer.VisualPropertiesGatherer.gatherNodeVisualProperties(VisualPropertiesGatherer.java:407)
	at org.cytoscape.io.internal.cx_writer.VisualPropertiesGatherer.gatherVisualPropertiesAsAspectElements(VisualPropertiesGatherer.java:83)
	at org.cytoscape.io.internal.cxio.CxExporter.writeVisualProperties(CxExporter.java:567)
	at org.cytoscape.io.internal.cxio.CxExporter.writeSubNetworks(CxExporter.java:1324)
	at org.cytoscape.io.internal.cxio.CxExporter.writeNetwork(CxExporter.java:239)
	at org.cytoscape.io.internal.cx_writer.CxNetworkWriter.run(CxNetworkWriter.java:259)

**Comment by AdamStuart** [comment]
??  I don't see CX as an optional format in the export dialog

**Comment by AlexanderPico** [comment]
Should be the first option...

<img width="750" alt="Screen Shot 2019-05-17 at 1 21 33 AM" src="https://user-images.githubusercontent.com/1418193/57913783-34c4d400-7842-11e9-9d75-535a85b4b66d.png">

**Comment by AdamStuart** [comment]
sorry, I'd uninstalled several core apps on home machine.

**Comment by AdamStuart** [comment]
looks like a problem inside CXWriter

org.cytoscape.io.internal.cx_writer.VisualPropertiesGatherer.addProperties(VisualPropertiesGatherer.java:101)
org.cytoscape.io.internal.cx_writer.VisualPropertiesGatherer.gatherNodeVisualProperties(VisualPropertiesGatherer.java:407)

**Comment by AlexanderPico** [comment]
Note that it is "fixed" by saving/loading the imported network as a session. This suggests the serialization to xgmml and back is "fixing" something the CXWriter cares about...

**Comment by AlexanderPico** [comment]
@ariutta This appears to be fixed in 3.3.8. Do you want to try skipping the save/close/reload steps in your next export to CX?
