### ISSUE TITLE
Some pathways not loading with 3.3.76

### ISSUE THREAD

**Issue by ariutta** [wikipathways/cytoscape-wikipathways-app#103]
Using version 3.3.76, I was able to load every pathway from the WP Curated set, except these three:
WP186, WP2289 and WP4297

Alex and I both tried them and got the same result.

(Moved issue from here: https://github.com/cytoscape/RCy3/issues/52)

**Comment by ariutta** [comment]
Still noticing this for Cytoscape version 3.7.1, WikiPathways App version: 3.3.77.

**Comment by AdamStuart** [comment]
Need more detail.   WP186 and WP4297 lose some coloring info, but otherwise they work for me.

**Comment by AlexanderPico** [comment]
Steps to reproduce:

1. Fresh launch of Cytoscape; fresh disable/enable of WP app
2. Search for WP186
3. Import at pathway (or network)

Obs: Empty network created (0 nodes; 0 edges) and the folloing task log

```
  Task (org.wikipathways.cytoscapeapp.impl.WPClientRESTImpl$2@5c62938d) title: Search WikiPathways for 'wp186'
  Task (org.wikipathways.cytoscapeapp.impl.WPClientRESTImpl$4@4b5e4e9e) title: Get 'Homologous recombination' from WikiPathways
  CyNetwork w/ public tables created: ID = 2234
  CyNetwork w/ public tables created: Base Graph ID = 2250
  Task (org.wikipathways.cytoscapeapp.impl.GpmlReaderFactoryImpl$ReaderTask@6d6061e8) title: Construct network
  Task (org.wikipathways.cytoscapeapp.impl.GpmlReaderFactoryImpl$ReaderTask@6d6061e8) status: Parsing pathways file
  Exception executing task: Pathway not available -- invalid GPML
```

And stacktrace:

```
11:34:17.976 ERROR [AWT-EventQueue-0] Error executing task: Pathway not available -- invalid GPML
java.lang.Exception: Pathway not available -- invalid GPML
	at org.wikipathways.cytoscapeapp.impl.GpmlReaderFactoryImpl$ReaderTask.run(GpmlReaderFactoryImpl.java:294)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.wikipathways.cytoscapeapp.impl.WPManager.loadPathway(WPManager.java:97)
	at org.wikipathways.cytoscapeapp.internal.guiclient.GUI.loadSelectedPathway(GUI.java:475)
	at org.wikipathways.cytoscapeapp.internal.guiclient.GUI.loadSelectedPathway(GUI.java:470)
	at org.wikipathways.cytoscapeapp.internal.guiclient.GUI$4.actionPerformed(GUI.java:166)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -23981
	at java.lang.String.substring(String.java:1967)
	at org.wikipathways.cytoscapeapp.impl.GpmlReaderFactoryImpl$ReaderTask.scrapePMIDs(GpmlReaderFactoryImpl.java:310)
	at org.wikipathways.cytoscapeapp.impl.GpmlReaderFactoryImpl$ReaderTask.run(GpmlReaderFactoryImpl.java:254)
	... 42 more
```

**Comment by AdamStuart** [comment]
Line 532 is an empty PMID:  <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string"/>
