### ISSUE TITLE
Ensembl mapping during import not working completely

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#108]
The auto mapping to Ensembl doesn't seem to be working properly. Just tried with AP app version 3.3.7 (released version) and latest CS (and also 3.7.1), and for the human Statin pathway, no mapping happens for Entrez Gene xrefs. Only two Ensembl Xrefs are properly propagated to the new Ensembl column.

As a comparison, BridgeDb maps all 30 Entrez IDs.

**Comment by AlexanderPico** [comment]
Here's the relevant bit of the stacktrace. Maybe the webservice url changed??
```
java.io.IOException: HTTP error code : 404
	at org.wikipathways.cytoscapeapp.internal.cmd.mapping.BridgeDbIdMapper.post(BridgeDbIdMapper.java:189)
	at org.wikipathways.cytoscapeapp.internal.cmd.mapping.BridgeDbIdMapper.runQuery(BridgeDbIdMapper.java:220)
	at org.wikipathways.cytoscapeapp.internal.cmd.mapping.BridgeDbIdMapper.map(BridgeDbIdMapper.java:63)
```

**Comment by AlexanderPico** [comment]
Indeed same `no response` from bridgedb webservice via swagger:
https://www.bridgedb.org/swagger/#!/Genes/post_organism_xrefsBatch_systemCode

This is a bridgedb bug, not a wikipathways app bug.
