### ISSUE TITLE
Pathway fails to load

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#49]
WP1591  has many shapes. Even it we can't reproduce the image completely, we do need to be able to open to the pathway. See error thrown...

![screen shot 2017-09-12 at 12 13 04 pm](https://user-images.githubusercontent.com/1418193/30343851-c3a06cbe-97b3-11e7-9240-fbed55aef0ea.png)

**Comment by AlexanderPico** [comment]
And WP2848 also fails to load. It's another pathway with a ton of shapes, but a different error...
![screen shot 2017-09-12 at 12 20 27 pm](https://user-images.githubusercontent.com/1418193/30344113-d860dd36-97b4-11e7-9407-1893b2224be2.png)

**Comment by AdamStuart** [comment]
java.lang.IllegalStateException: Invalid angle: NaN. Cuased by cos(theta) = NaN
	at org.cytoscape.ding.impl.HandleImpl.convertToRatio(HandleImpl.java:175)
	at org.cytoscape.ding.impl.HandleImpl.defineHandle(HandleImpl.java:107)
	at org.cytoscape.ding.impl.HandleImpl.<init>(HandleImpl.java:54)
	at org.cytoscape.ding.impl.HandleFactoryImpl.createHandle(HandleFactoryImpl.java:36)
	at org.wikipathways.cytoscapeapp.DelayedVizProp.applyEdgeBend(DelayedVizProp.java:376)

**Comment by AdamStuart** [comment]
java.lang.IllegalArgumentException: width is too small
	at org.cytoscape.ding.impl.DNodeView.setWidth(DNodeView.java:354)
	at org.cytoscape.ding.impl.DNodeView.applyVisualProperty(DNodeView.java:1021)
	at org.cytoscape.ding.impl.AbstractDViewModel.setLockedValue(AbstractDViewModel.java:150)
	at org.wikipathways.cytoscapeapp.DelayedVizProp.applyAll(DelayedVizProp.java:100)
	at org.wikipathways.cytoscapeapp.GpmlReaderFactoryImpl$ApplyVizProps.run(GpmlReaderFactoryImpl.java:207)
