### ISSUE TITLE
empty node table and missing names in edge table

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#84]
Testing new 3.3.4 jar with 3.7.

* Lots of printout statements
* Searched for ‘statin’.  Got results that included “Test pathways”, e.g., WP3590. Should we only allow “Approved” pathways through? Or perhaps exclude “Test” and “Marked for Deletion”?  Did you change the webservice query?
* Preview works well
* Imported as pathway

Obs: new pathway, but blank Node Table and unnamed rows in Edge Table
Exp: full Node and Edge Tables

Threw NPE:

> turnOffEvents
turnOnEvents
turnOffEvents
turnOnEvents
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.cytoscape.browser.internal.view.BrowserTableModel.setValueAt(BrowserTableModel.java:474)
	at javax.swing.JTable.setValueAt(JTable.java:2744)
	at javax.swing.JTable.editingStopped(JTable.java:4729)
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141)
	at javax.swing.AbstractCellEditor.stopCellEditing(AbstractCellEditor.java:85)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1010)
	at javax.swing.plaf.basic.BasicTableUI$MouseInputHandler.mousePressed(BasicTableUI.java:798)
	at org.cytoscape.browser.internal.view.BrowserTable$ProxyMouseListener.mousePressed(BrowserTable.java:1010)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by AlexanderPico** [comment]
Reproduced NPE error after restart. However, within the SAME session, following the NPE, I was able to import-as-network and also import-as-pathway and got full tables!?

**Comment by AlexanderPico** [comment]
Another oddity... if you select a node, then it shows up in the node table!  But unselected (auto mode) or even "show all" mode fail to display any rows.
